version: '3.9'
services:
  api:
    build: .
    ports:
      - "8000:80"
    env_file:
      - ./.env
    depends_on:
      - db
    # volumes:
    #   - ./:/usr/src/app:ro
    develop:
      watch:
        - action: sync
          path: .
          target: /usr/src/app
        - action: rebuild
          path: ./requirements.txt
    command: ["fastapi", "dev", "app/main.py", "--host", "0.0.0.0", "--port", "80"]
       

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: fastapi_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: